import Link from "next/link";
import { BsInstagram, BsTelegram, BsWhatsapp } from "react-icons/bs";
import Image from "next/image"
// import Logo from "../public/spade.png"
import Logo from "./Logo"

const Footer = () => {
    return (
        <>
            <div className="md:mt-8 lg:mt-16 flex flex-col justify-center items-center text-white break-words bg-black overflow-hidden border-t-2 border-opacity-20 border-white">
                <div className="grid grid-cols-8 text-black break-words text-center mt-4 lg:mt-12 gap-4">
                    <div
                        className="col-span-4 md:col-span-2 py-3 px-4 text-sm text-white bg-primary hover:bg-opacity-80 cursor-pointer"
                    >
                        <Link
                            href="/"
                            className="break-words bg-transparent"
                        >Introduction</Link>
                    </div>
                    <div
                        className="col-span-4 md:col-span-2 py-3 px-4 text-sm text-white bg-primary hover:bg-opacity-80 cursor-pointer"
                    >
                        <Link
                            href="/"
                            className="break-words bg-transparent"
                        >How to register</Link>
                    </div>
                    <div
                        className="col-span-4 md:col-span-2 py-3 px-4 text-sm text-white bg-primary hover:bg-opacity-80 cursor-pointer"
                    >
                        <Link
                            href="/"
                            className="break-words bg-transparent"
                        >How to deposit</Link>
                    </div>
                    <div
                        className="col-span-4 md:col-span-2 py-3 px-4 text-sm text-white bg-primary hover:bg-opacity-80 cursor-pointer"
                    >
                        <Link
                            href="/"
                            className="break-words bg-transparent"
                        >How to use bonus</Link>
                    </div>
                </div>

                <div className="flex justify-center items-center pt-4 text-3xl font-bold text-center text-white break-words cursor-pointer mt-6 hover:opacity-80">
                    <div className="inline-block relative my-0 mx-2 font-bold text-white">
                        <BsWhatsapp className="" />
                    </div>
                    <div className="font-bold text-white cursor-pointer">WHATSAPP US!</div>
                </div>

                <div className="flex flex-row justify-center items-center pt-4 text-3xl font-bold text-center text-white break-words cursor-pointer mt-6 mb-12">
                    <div className="inline-block relative my-0 mx-2 font-bold text-white hover:opacity-80">
                        <BsTelegram className="" />
                    </div>
                    <div className="inline-block relative my-0 mx-2 font-bold text-white hover:opacity-80">
                        <BsInstagram className="" />
                    </div>
                </div>

                <div className="flex flex-col lg:flex-row items-center pl-2 break-words max-w-[90vw]">
                    <Link href="/about" className="opacity-70">
                        <Logo />
                    </Link>
                    <p className="text-xs font-normal text-left text-white py-6 px-2 lg:px-4 max-w-5xl">
                        Spade 365 is operated by XYZ Company, registered in Curacao and is licensed and regulated by the Curacao authority as the
                        regulatory body responsible holding a Players
                        are requested not to contact any untrusted sources for Spade365 accounts as
                        this is an online site and they can only register independently without any
                        agents. Only deposit through the account details generated by the system or
                        provided by our official support team.
                    </p>
                </div>

                {/* paytm, upi etc  */}
                <div className="grid grid-cols-3 md:grid-cols-6 text-black break-words text-center mt-4 lg:mt-12 gap-4 md:gap-12 lg:gap-24 px-4 pb-12 max-w-[300px] md: md:max-w-3xl xl:max-w-5xl">
                    <div>
                        <Image className="opacity-40" src="/img/paytm.png" alt="spade" width={200} height={73} quality={10} />
                    </div>
                    <div>
                        <Image className="opacity-40" src="/img/upi.png" alt="spade" width={200} height={73} quality={10} />
                    </div>
                    <div>
                        <Image className="opacity-40" src="/img/bank-transfer.png" alt="spade" width={200} height={73} quality={10} />
                    </div>
                    <div>
                        <Image className="opacity-40" src="/img/gamble-aware.png" alt="spade" width={200} height={73} quality={10} />
                    </div>
                    <div>
                        <Image className="opacity-40" src="/img/gambling-commission.png" alt="spade" width={200} height={73} quality={10} />
                    </div>
                    <div>
                        <Image className="opacity-40" src="/img/mga.png" alt="spade" width={200} height={73} quality={10} />
                    </div>
                </div>
            </div>
        </>

    )
}

export default Footer